### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by ialokim** [lamudi-gmbh/android-phone-field#19]
I just wanted to know if there is still someone maintaining this library or if someone knows about any active fork of it?

(especially pinging @ialmetwally, @fouadkada, @mherod as they were committing on here or at some fork)

**Comment by fouadkada** [comment]
I'm not putting any effort in this project in the foreseeable future

Best,
Fouad

**Comment by ialokim** [comment]
Thanks for your reply!

I've now forked the project and added quite a lot of enhancements, please refer to [ialokim/android-phone-field](/ialokim/android-phone-field) if someone else is searching for an active fork.
